version: "3.9"

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped

    volumes:
      - /srv/filebrowser/data:/data
      - /srv/filebrowser/config:/config

    networks:
      - highfishNetwork

    # ports:
    #   - "8080:8080"

networks:
  highfishNetwork:
    external: true
